apply plugin: "com.liferay.custom.cxinstances"

File clientExtensionsDir = file("client-extensions")

boolean deployEnvSet = findProperty("cx.custom.deploy.env") as boolean

boolean standaloneTaskRequested = gradle.startParameter.taskNames.any { String taskName ->
	["generateCXConfig", "retrieveCXInstances"].any { taskName == it || taskName.endsWith(":" + it) }
}

boolean onePerInstance = String.valueOf(findProperty("cx.custom.one-per-instance")) == "true"

boolean nestedInstanceRun = findProperty("cx.internal.instance.web.id") != null

subprojects { Project subproject ->
	if (!subproject.projectDir.toPath().startsWith(clientExtensionsDir.toPath()) ||
		!subproject.file("client-extension.yaml").exists()) {

		return
	}

	subproject.afterEvaluate {
		if (!subproject.pluginManager.hasPlugin("com.liferay.custom.cxconfig")) {
			subproject.pluginManager.apply("com.liferay.custom.cxconfig")
		}

		if (nestedInstanceRun) {
			if (!subproject.pluginManager.hasPlugin("com.liferay.custom.cxperinstance")) {
				subproject.pluginManager.apply("com.liferay.custom.cxperinstance")
			}

			return
		}

		if (!deployEnvSet || standaloneTaskRequested) {
			return
		}

		String pluginId = onePerInstance ? "com.liferay.custom.cxperinstance" : "com.liferay.custom.cxmultiinstance"

		if (!subproject.pluginManager.hasPlugin(pluginId)) {
			subproject.pluginManager.apply(pluginId)
		}
	}
}
